### ISSUE TITLE
question about the paper

### ISSUE THREAD

**Issue by wuyaxi98** [fedecaccia/Online-News-Clustering#2]
hello! i had read your code,it is well work ,but you may not  implement emergency monitoring in the paper.

**Comment by fedecaccia** [comment]
@wuyaxi98 I don't understand what you mean.. The code does not give an alarm when it detects a big braking news cluster (yet), is that what you mean?

**Comment by wuyaxi98** [comment]
I mean, there is no  Detection of bursty terms in clusters and Event detection in this work.Beautiful results, just showing the cluster with a large number of tweets ,but not the bursty event

**Comment by wuyaxi98** [comment]
@fedecaccia ,A few days ago, I was confused and could not find it,there is no the bursty event fuction? !

**Comment by fedecaccia** [comment]
@wuyaxi98 I think you are missunderstanding the project. This code is not an implementation of any paper. The code performs an incremental clustering algorithm over news and social media articles. If you use it online on the news of the moment, it is useful to detect clusters, and then, detect bursting topics of the moment. The _tf-idf_ representation of each centroid cluster can serve to detect the bursting terms.

**Comment by wuyaxi98** [comment]
@Koltharius i see! thank you for much. and i think the  bursting topics of the moment is the topic with more tweets in the project
